module.exports = {
  siteUrl: 'https://mip.institute',
  changefreq: 'daily',
  priority: 0.7,
  sitemapSize: 5000,
  generateRobotsTxt: true,
  generateIndexSitemap: false,
  exclude: ['/payment','/gratefull', '/promo*', '*?', '/seminars'],
  transform: async (config, path) => {
    return {
      loc: path, // => this will be exported as http(s)://<config.siteUrl>/<path>
      changefreq: config.changefreq,
      priority: config.priority,
      lastmod: config.autoLastmod ? new Date().toISOString() : undefined,
      alternateRefs: config.alternateRefs ?? []
    }
  },
  robotsTxtOptions: {
    policies: [
      {
        userAgent: '*',
        allow: ['/*.css', '/*.js', '/*.jpg', '/*.png', '/*.gif'],
        disallow: ['/promo*', '*?', '*test', '/kz', '/ru', '/uz', '*?calltouch_', '*%', '/docs/', '/policies/', 
        '/professions/prakticheskaya-psihologiya/psihosintez-v-psihoterapevticheskoj-praktike$', 
        '/professions/konsultirovanie/semejnoe-psihologicheskoe-konsultirovanie$', 
        '/professions/klinicheskaya-psihologiya/klinicheskij-psiholog$', 
        '/professions/detskaya-psihologiya/defektolog$', 
        '/professions/dietologiya-i-nutriciologiya/nutriciologiya$', 
        '/professions/konsultirovanie/semejnyj-psiholog$', 
        '/professions/obshaya-psihologiya/psihologiya-lichnosti$',
        '/professions/konsultirovanie/prakticheskij-psiholog$', 
        '/professions/prakticheskaya-psihologiya/prakticheskij-psiholog$', 
        '/professions/konsultirovanie/psihologicheskoe-internet-konsultirovanie$', 
        '/professions/organizacionnaya-psihologiya/prakticheskaya-konfliktologiya-i-mediaciya$', 
        '/professions/konsultirovanie/prakticheskaya-konfliktologiya-i-mediaciya$', '/professions/korporativnaya-psihologiya/psiholog-biznes-konsultant.-kouch$', 
        '/professions/konsultirovanie/psihodiagnostika-detej-i-vzroslyh-v-prakticheskoj-psihologii$', 
        '/professions/konsultirovanie/skazkoterapiya-v-psihologicheskom-konsultirovanii$', 
        '/professions/organizacionnaya-psihologiya/$', 
        '/professions/obshaya-psihologiya/$', 
        '/professions/obshaya-psihologiya/psihologiya$', 
        '/professions/konsultirovanie/psihologicheskoe-konsultirovanie-detej-i-podrostkov$', 
        '/professions/konsultirovanie/psihodiagnostika-v-psihologicheskom-konsultirovanii$', 
        '/professions/prakticheskaya-psihologiya/socialnyj-psiholog$', '/professions/obshaya-psihologiya/socialnyj-psiholog$', 
        '/professions/konsultirovanie/metaforicheskie-karty-v-psihologicheskom-konsultirovanii$', 
        '/professions/psihoterapiya/psihosintez-v-psihoterapevticheskoj-praktike$', 
        '/professions/konsultirovanie/psihologicheskoe-konsultirovanie-i-diagnostika-lichnosti$', 
        '/professions/organizacionnaya-psihologiya/psihologiya-obsheniya-v-delovoj-sfere$', 
        '/professions/konsultirovanie/osnovy-psihologicheskogo-konsultirovaniya-i-professionalnyj-kouching$', 
        '/professions/konsultirovanie/teoriya-i-praktika-individualnogo-i-semejnogo-konsultirovaniya$', 
        '/professions/konsultirovanie/pesochnaya-terapiya-v-psihologicheskom-konsultirovanii$', 
        '/professions/konsultirovanie/proektivnye-metodiki-v-psihologicheskom-konsultirovanii$', 
        '/professions/konsultirovanie/konsultirovanie-v-sfere-seksualnyh-otnoshenij$', 
        '/professions/konsultirovanie/kratkosrochnaya-psihoterapiya$', 
        '/professions/konsultirovanie/psiholog-konsultant/$', 
        '/professions/psihoterapiya/psihosomatika-i-telesnaya-psihoterapiya/$',
        '/professions/pedagogika/logoped-s-dop.-kvalifikaciej-specialnyj-psiholog$',
        '/programs/etika-professionalnoj-deyatelnosti-psihologa$',
        '/professions/konsultirovanie/kognitivno-povedencheskij-psihoterapevt$',
        '/courses/prakticheskaya-psihologiya$',
        '/professions/pedagogika$',
        '/professions/gipnoz/suggestivnaya-psihologiya.-gipnoz-v-psihologicheskom-konsultirovanii$',
        '/professions/pedagogika/pedagog---psiholog$',
        '/professions/konsultirovanie/mediator$',
        '/professions/samoregulyaciya-psihologicheskogo-zdorovya$',
        '/courses/samoregulyaciya-psihologicheskogo-zdorovya$',
        '/programs/prakticheskaya-psihologiya$',
        '/professions/konsultirovanie/sportivnyj-psiholog$',
        '/courses/gipnoz$',
        '/professions/konsultirovanie/telesno-orientirovannaya-terapiya$',
        '/professions/prakticheskaya-psihologiya/psihologiya-lichnosti$',
        '/professions/korporativnaya-psihologiya/prakticheskaya-konfliktologiya-i-mediaciya$',
        '/professions/konsultirovanie/prakticheskij-psiholog-s-dop.-kvalifikaciej-psiholog-psihoterapevt$',
        '/professions/prakticheskaya-psihologiya/psihologiya-obsheniya-v-delovoj-sfere$',
        '/courses/konsultirovanie/sovremennye-metody-samoregulyacii-psihologii-zdorovya$',
        '/professions/konsultirovanie/psihoanaliz-i-psihologicheskaya-psihoterapiya$',
        '/courses/socialnaya-psihologiya$',
        '/professions/prakticheskaya-psihologiya$',
        '/courses/konsultirovanie/sovremennaya-kognitivno-povedencheskaya-terapiya$',
        '/courses/konsultirovanie/narcissizm-i-narcissicheskie-rasstrojstva$',
        '/professions/korporativnaya-psihologiya$',
        '/professions/defektologiya/defektolog$',
        '/courses/konsultirovanie/psihologiya-semi-i-semejnyh-vzaimootnoshenij$',
        '/programs/gipnoz$',
        '/professions/korporativnaya-psihologiya/korporativnyj-psiholog$',
        '/professions/dietologiya/nutriciologiya$',
        '/courses/konsultirovanie/psihologiya-vospitaniya$',
        '/professions/prakticheskaya-psihologiya/pesochnaya-terapiya-v-psihologicheskom-konsultirovanii$',
        '/courses/konsultirovanie/bazovye-navyki-geshtalt-terapii$',
        '/professions/konsultirovanie/detskij-psiholog$',
        '/professions/dietologiya/psiholog-dietolog$',
        '/courses/konsultirovanie/psihologiya-obsheniya$',
        '/professions/kouching$',
        '*undefined']
      }
    ]
  }
}