export const OPEN_MENU = 'OPEN_MENU'
export const CLOSE_MENU = 'CLOSE_MENU'
export const TOGGLE_MENU = 'TOGGLE_MENU'
export const OPEN_OVERLAY = 'OPEN_OVERLAY'
export const CLOSE_OVERLAY = 'CLOSE_OVERLAY'
export const TOGGLE_OVERLAY = 'TOGGLE_OVERLAY'
